name: task-manager

services:
  postgres_db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - manage_data:/var/lib/postgresql/data
    networks:
      - manage-network
    ports:
      - "${DB_PORT}:5432"
    healthcheck: # ← ДОБАВЬТЕ ЭТОТ БЛОК!
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile  # явно укажите
    container_name: manage-app
    ports:
      - "${APP_PORT}:8080"  # порт из Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - manage-network

volumes:
  manage_data:

networks:
  manage-network:
    driver: bridge

