spring:
  application:
    name: app
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always                 # ✅ Цветной вывод

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"  # ✅ Формат даты

app:
  welcome-message: "Welcome to Spring"

server:
  port: 8080